### ISSUE TITLE
Message from Unknown bug

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-mac#100]
i tried to send a message in a tribe with a picture and some text. It came out looking like this:
<img width="746" alt="Screenshot 2023-07-06 at 9 41 12 AM" src="https://github.com/stakwork/sphinx-mac/assets/104323003/0f1b503f-7afd-4fec-9d4c-7aa63416a1f4">

I think I'm the "Unknown". But looks like Ali was able to see it normally.

**Comment by tomastiminskas** [comment]
This is a known bug but will be fixed with the refactor

**Comment by tomastiminskas** [comment]
Fixed on the refactored version
