### ISSUE TITLE
Logging into Sphinx in Browser Not Possible if App Closed

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-mac#104]
If the app is not running and the user attempts to login through the community.sphinx.chat page, the authorization button does not ever appear and the user is required to retry.

Steps to recreate:
1. Quit all instances of Sphinx Mac
2. Go to the community.sphinx.chat/tickets page
3. Click sign in
4. Click sign in through Sphinx
5. The app will launch itself but will not actually present the user with the authorization window like it ought to

**Comment by tomastiminskas** [comment]
@tomsmith8 will be fixed in build 286 going out soon
