### ISSUE TITLE
Update mention of LSAT for L402

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#108]
**Task**

We need to update any mention of LSAT to L402 inside the SecondBrain.

Balance and tapping on balance, opens a sphinx window and therefore changes are required all repositories for Sphinx (Mac, iOS, kotlin for android & Dekstop).

Mac being the priority as that is what Paul uses for Demo's.

**Current** 

We should update all mentions to L402 (I think this is the only area it appears)

![LSATlist](https://github.com/stakwork/sphinx-mac/assets/142233216/3439e6ec-eb8c-42bc-bfda-03bd2f1ff222)

**Comment by tomastiminskas** [comment]
I'm on it @tomsmith8 . I will upload a version to TF with the change during the day

**Comment by tomastiminskas** [comment]
@tomsmith8 changes are done and they will be released in a new version going out soon. Will keep you posted
