### ISSUE TITLE
'Today' bar inserted on the same day

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#110]
**Task**

As per the image below, the new macOS release v1.1.0 (285) inserted a “Today” link in between messages that were just 20 minutes apart on the same day.

![Image](https://user-images.githubusercontent.com/142233216/265935214-a6c6035f-e566-4c30-bb4f-80212d1edc9e.png)

**Comment by tomastiminskas** [comment]
@tomsmith8 I couldn't find an example of this issue on the tribes I joined. I will keep an eye to see if I can reproduce it, then I will be able to fix it. If you experience it in any of the tribes I'm in, please point it to me.

**Comment by tomastiminskas** [comment]
@tomsmith8 I could reproduce it so I will fix it for new release and keep you posted here

**Comment by tomastiminskas** [comment]
@tomsmith8 I couldn't reproduce it, so let's keep an eye on it and let me know when you can point me to a tribe where it's happening
