### ISSUE TITLE
Tapping a link within a message needs fixing

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#112]
**Task**

Currently, when tapping a link inside Sphinx on Mac/Desktop it is rather annoying. Sometimes links work, sometimes they do not, sometimes it starts adding itself as an attachment?

Let's fix that for UX gains.

**Acceptance Criteria**

- When link is provided alone - tapping anywhere on the url should open it smoothly
- When link is provided with text - tapping anywhere on the url should open it smoothly
- Tapping should never start adding as an attachment?

**Comment by tomastiminskas** [comment]
@tomsmith8 could you provide a message example with a link that doesn't work? The logic to handle link clicks in message bubbles is complex so seems to be an issue that happens in very specific conditions. I just tested and couldn't reproduce it. Here is a video:


https://github.com/stakwork/sphinx-mac/assets/2242281/a34ecb9b-6088-49ea-9412-2a57cc37debe
