### ISSUE TITLE
Misalignment of fields when restoring keys

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#113]
**Task**

For macOS, when you restore the app using your keys, the alignment on the key entry field and some other fields during that process are off.

Note, I'll try and recreate and provide screen shot but imagine it's obvious.

**Acceptance Criteria**

- All entry fields are aligned

**Comment by tomastiminskas** [comment]
@tomsmith8 will be fixed in build 286 going out soon
