### ISSUE TITLE
Access to Second Brain isn't obvious in Sphinx UI

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#114]
**Task**

Access to SecondBrain isn't obvious inside a Tribe. 

**Design**

- What improvements can we make here?
- Change icon? different user journey?

**Desktop**

- Change the icon to SecondBrain icon

**Mobile**

- Remove from header
- Add to three dots
- Priortise other feature (threads, search)

**Comment by tomastiminskas** [comment]
@Antanasijevic I think this is something you should help us with. I can implement any design you propose.

**Comment by Antanasijevic** [comment]
> @Antanasijevic I think this is something you should help us with. I can implement any design you propose.

Yes, im working on it. I will post few options soon so we can consult

**Comment by Antanasijevic** [comment]
![image](https://github.com/stakwork/sphinx-mac/assets/13258550/bccb77df-c115-416c-bcbd-558950680d3d)
