### ISSUE TITLE
Copying and pasting a link in Sphinx creates an attachment

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#115]
**Task**

See video:

https://user-images.githubusercontent.com/142233216/266638833-a8db0c3c-9f55-4099-9952-6f73d0b4b9d0.mov

When copying a link in Sphinx and pasting it, it tries to add it as an attachment.

**Comment by tomastiminskas** [comment]
@tomsmith8 will be fixed in build 286 going out soon
