### ISSUE TITLE
Multiple Dings when joining new tribe

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#116]
Expected Behaviour

I would expect to receive only 1 'ding' MAX.

Actual Behaviour

Ding, Ding, Ding etc

Steps to recreate

- Join a new tribe (Assume there would need to be messages beforehand)
- Ding, Ding, Ding 🔔

**Comment by tomsmith8** [comment]
@tomastiminskas I guess this is across all Apps?

**Comment by tomastiminskas** [comment]
@tomsmith8 No, this is specific to Mac. We had something to prevent this but I might have broken it. I will put it back

**Comment by tomastiminskas** [comment]
@tomsmith8 will be fixed in build 286 going out soon
