### ISSUE TITLE
Double attachment when sending attachment

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#117]
**Task**

Sometimes when sending an attachment, for a short period of time a double attachment appears:

![Image](https://user-images.githubusercontent.com/142233216/266001600-9983594c-ab0b-4038-ad3e-2fe253eb5f29.png)

This does eventually go but harms UX.

**Comment by tomastiminskas** [comment]
@tomsmith8 this will be fixed with the refactor I'm working on
