### ISSUE TITLE
Adding Contact issue (no route hint)

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#118]
**Task**

Sometimes when I add a contact it doens't grab the route hint. I then try to send a message I get message failure.

The only way it seemed to fix for me is to re-add the contact.

Note: this doesn't happen on all contacts but unsure why it does for some?

![Image](https://user-images.githubusercontent.com/142233216/265792126-c3f5c761-925c-48bc-825c-bc9b255c939c.png)

**Comment by tomastiminskas** [comment]
@tomsmith8 will be fixed in build 286 going out soon
