### ISSUE TITLE
Drag n drop causes encryption error

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#119]
**Task**

Ed ran into an issue where he attmepted to drag and drop a file on Sphinx Mac and it gave him an encryption error? Messages were going through fine?

![Image](https://user-images.githubusercontent.com/142233216/265936423-27a3448d-af47-4171-a458-3e5af39922c1.png)

**Comment by tomastiminskas** [comment]
@tomsmith8 this is the issue on memes server with uploads. I will change the error message to be more descriptive and express what the actual error is. But not something related with encryption actually

**Comment by tomastiminskas** [comment]
@tomsmith8 will be fixed in build 286 going out soon
