### ISSUE TITLE
Open image on click (For bot responses)

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#120]
**Task**

Apps should be able to enlarge an image from a bot response when clicked on (like a normal image attachment). Bot responses are HTML with embedded images in them.

**Outcome**

- Bot responds with an image
- You click on the image
- It should enlarge the image (like a normal image attachment)

**Comment by uncleJim21** [comment]
@tomsmith8 this should be live as of the latest testflight build. Try it out and if you approve let's close this one out.

**Comment by tomsmith8** [comment]
Tested and looked good to me! closing
