### ISSUE TITLE
Notification icon on App Icon

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#121]
Currently when you receive a notification or message Sphinx App it doesn't show a notification on the icon?

e.g. 

![Image](https://user-images.githubusercontent.com/142233216/266003335-ff071359-e5ec-4c3f-a1a1-e90e73a6c14d.png)

We should 100% show a red notification icon

**Comment by uncleJim21** [comment]
@tomsmith8 I took a look at this and I think this is an issue with your System Settings (beyond our control). You need to do the following:
Go to Settings -> Notifications -> Sphinx -> Allow Notifications (on) -> Alerts

Let me know if this works for you and if so I will close this out.
![image](https://github.com/stakwork/sphinx-mac/assets/96802642/f6439a41-a497-469c-8dd1-a71f295ec512)

**Comment by tomsmith8** [comment]
wow, boomer moment here. Sorted, thanks Jim!
