### ISSUE TITLE
Incorrect profile pic in Tribe

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#122]
On Mac, I Kevin's image pulled through rather than Rasul's:

Tribe is SecondBrain:

![Image](https://user-images.githubusercontent.com/142233216/267666592-5906e1be-1c9e-4167-af67-4c1e2c8c8838.png)

Not sure why this happened?

**Comment by tomsmith8** [comment]
Fixed by going off/on the tribe.

**Comment by uncleJim21** [comment]
@tomsmith8 this is a common issue that occurs in Apple applications where the app is trying to optimize memory and it may do odd things like this. This may or may not be the problem. I'll take a look and see if I can override this behavior however I do think it will be quite difficult to recreate which makes proving the solution much harder to prove🙃. If you can provide any tips/details on increasing the likelihood of observing the problem that'd be awesome.

**Comment by tomsmith8** [comment]
I haven't actually seen it occur that often or at all in the last week FYI. Will keep it open for now..

**Comment by tomsmith8** [comment]
Still haven't seen this in ages. I'm going to close for now and we can reopen if we see this again
