### ISSUE TITLE
Issue with no response between two lite users

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#132]
**Issue**

https://www.loom.com/share/33555a7f46b54479997db98c56fdaa32?sid=42316fbd-63a1-498a-a185-84942c3df5cc

- Ed added user via Bounties people page
- Ed messaged user and you can see the 3 messages within Loom
- User has said he responded back (we know this from Andrew) but as you can see Ed hasn't received a message
- We need to investigate but unsure where the issue lies

**Comment by Edvardoh** [comment]
![sphinx fri 29 sep 09 54 06](https://github.com/stakwork/sphinx-mac/assets/5913805/4806aa81-6d80-4548-87a1-4a010164ce38)

**Comment by Edvardoh** [comment]
Yep that's right - also here are some screenshots - Andrew passed along the screenshot from his end, and then the next one is what I see from my end.

<img width="404" alt="Screenshot 2023-09-29 at 9 55 06 AM" src="https://github.com/stakwork/sphinx-mac/assets/5913805/2e65a4c5-fa67-4caa-b1ed-0835af98d725">
<img width="720" alt="Screenshot 2023-09-29 at 9 55 14 AM" src="https://github.com/stakwork/sphinx-mac/assets/5913805/8620da73-ef9d-4bde-b5e5-52d6d62ca2bc">

**Comment by tomsmith8** [comment]
We've seen this issue with other users and Kevin/Evan have just put a fix out for it.

For this case, if you delete and re-add eachother, it should fix it.

The issue happened on the key swap page where Martin didn't have sats to do the swap (I believe 3-6 sats is required).

Closing issue but will reopen if we see this again.
