### ISSUE TITLE
Difficult to tap link with two links

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#137]
**Task**

As per the Loom video, it's very tricky to tap the link url link

Variables:

- Two Links sent
- Tagged users

https://www.loom.com/share/be6ed37a9ae541628d40788d823ddc5b?sid=22f1a105-4c95-4637-b815-10b9ee29a80b

**Comment by tomsmith8** [comment]
Weirdly enough this only works with my Mac mouse and not the trackpad.. maybe it's just a local issue

**Comment by uncleJim21** [comment]
@tomsmith8 thanks for the heads up. I likewise am unable to recreate with an external mouse (I happen to have a Logitech) but maybe it is something to do with the way the mac specific mouse works?

At any rate, can you be more specific about in what way it is difficult? It can't be seen from your video but I assume you are furiously clicking at not able to open the link unless you hit it in the right spot? 

What do you observe with the trackpad?

On my test I was able to instantly click each link with zero issues. I will see if I can get a hold of a mac mouse for my own tests.

**Comment by uncleJim21** [comment]
@tomsmith8 update: I tried this with an apple a1657 "magic mouse" and I did not observe the issue. So I suspect it is either something with the hardware you have or otherwise specific to your system settings.

**Comment by tomsmith8** [comment]
Thanks @uncleJim21 - The trackpad works fine. I'll check my settings but it could be a hardware issue - I've actually started noticing it in Stakwork work flows for specific buttons..

I was furiously clicking yes haha so I assume it is a me problem so we could close?
