### ISSUE TITLE
Amount field not becoming active when clicked during payment flow

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#146]
The issue is the amount field not becoming active when clicked

https://www.loom.com/share/4485e3443c8846349901f6694afd7931?sid=90c5590f-b915-440f-b3f5-9480ee9f149f

**Comment by uncleJim21** [comment]
@Edvardoh @tomsmith8 is this still a consistent issue on 290/291? I just tried both and I didn't observe it.

What model of Mac are you using & what chipset?

**Comment by Edvardoh** [comment]
@uncleJim21 It seems to have resolved - I'm not having the issue anymore on 291 and am able to click to edit the amount and send sats no problem
