### ISSUE TITLE
Remaining Budget on Second Brain

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#149]
Instead of showing it on the app over the second brain WebViews, app should notify Second Brain using the bridge and the Second Brain webpage should show it integrated in the design

**Task**

The `Remaining Budget` in secondbrain is showing on the app over second brain webview. 

This should be sent from the app to second brain and the second brain should show it.

Both the budget setting popup modal and the budget itself is displayed by the host app:
- We need to send the remaining balance from the app to SB via bridge
- We can remove the frontend UI from host apps
- Implement set budget modal [here](https://www.figma.com/file/YuEbi4x32Mm8ZQJdnrs4uc/Second-Brain-Final-Designs?type=design&node-id=1372-13196&mode=design&t=9vHjmw2LuzQKIHBB-0)
- Implement budget based on SB design [here](https://www.figma.com/file/YuEbi4x32Mm8ZQJdnrs4uc/Second-Brain-Final-Designs?type=design&node-id=1372-13196&mode=design&t=9vHjmw2LuzQKIHBB-0)

**Comment by uncleJim21** [comment]
@tomastiminskas I can take this. It seems like it would be as simple as sending the correct message using the sendMessage function in WebAppHelper.

Does Second Brain already have a parameter that it is looking for regarding budget or do we need to make updates to second brain as well before this is possible?

**Comment by tomastiminskas** [comment]
I don't think Second Brain is already supporting this, so you should talk to @kevkevinpal or someone on that side to work on this together. App should send the remaining budget to SB via bridge and SB should show it as part of the web UI. We might need some designs from @Antanasijevic for that

**Comment by uncleJim21** [comment]
Ok it seems like the relay may already have this information so it would be a matter of either calling an additional API or making sure that the relay syncs with SB.  I am looking here:
<img width="1014" alt="image" src="https://github.com/stakwork/sphinx-mac/assets/96802642/424a8ee4-2931-4c86-a625-ed54713c88ee">
And I see the existing chain of events goes something like:
didReceiveMessage -> saveGraphData ->  API.saveGraphData (calls action_history endpoint) -> sendLsatResponse -> update Remaining Budget UI.

So it appears there's already a chain of events that syncs the relay & the application

**Comment by uncleJim21** [comment]
@kevkevinpal I took a look at this and I think it doesn't make sense to have the client track the budget. If it does, it leaves the possibility of abuse (imagine a deadbeat that just writes JS that says he always has a sufficient budget).

Instead SecondBrain should track the budget and either provide an endpoint for the client to query or better yet just display the information itself.

Once that is live I can make the necessary adjustments to see this through to completion.

**Comment by uncleJim21** [comment]
@kevkevinpal circling back to this. I think this warrants a brief call. Let's pick a day in the next few business days to hash out a strategy.

**Comment by tomastiminskas** [comment]
@uncleJim21 I might be wrong but @tobi-bams was taking care of it. We already remove the label from sphinx app and he implemented a new message type between app and web view using the js bridge, so now SB will ask the app for the remaining budget and it will be shown as part of the web.

**Comment by tobi-bams** [comment]
> @uncleJim21 I might be wrong but @tobi-bams was taking care of it. We already remove the label from sphinx app and he implemented a new message type between app and web view using the js bridge, so now SB will ask the app for the remaining budget and it will be shown as part of the web.

Exactly, this is how we have it implemented.
