### ISSUE TITLE
Thread row issues

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#151]
Sometimes a thread row is showing even when original message has just 1 reply

![sphinx wed 11 oct 01 28 34](https://github.com/stakwork/sphinx-mac/assets/2242281/13209c08-313c-4b1b-8b4e-6e0b5070be0b)

**Comment by tomsmith8** [comment]
@tomastiminskas image doesn't load for me so not 100% sure what I should be testing here? Could you confirm the issue and close if fixed?
