### ISSUE TITLE
Improve display for threads to know which tribe you are in

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#165]
**Task**

When reading a thread, it isnt clear which tribe you are in:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/41b8251b-bdf2-4f01-a9e6-e3dda5e7a887)

Example: so this shot looks like I’m DMing Tobi. Maybe showing the tribe name next to the arrow on the upper left indicates it will  return the user to the tribe chat

**Comment by pitoi** [comment]
This looks good, I had one thought that it would be nice to indicate which thread is currently highlight in the side bar. So in this example this block would be have a border or have an inidicator directing attention to the sidebar:

<img width="265" alt="Screenshot 2023-12-11 at 10 26 23" src="https://github.com/stakwork/sphinx-mac/assets/814886/2ef25518-590f-4ea0-aa5d-63081db98eba">

**Comment by Antanasijevic** [comment]
Here is a possible way we could highlight opened thread.

https://github.com/stakwork/sphinx-mac/assets/13258550/5da18c0c-155c-40bc-8ff6-133b21eecdd7

**Comment by tomsmith8** [comment]
Looks great!
