### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#169]
Use “test-flight” branch

**Task**

We're seeing Memory increasing exponentially when switching chats. App becomes unusable for some users after a day or so.

Investigate issue and provide fix for memory leaks caused by switching between chats.

**Acceptance Criteria**

- [ ] Use “test-flight” branch
- [ ] Fix Memory Leak issues

**Comment by tomsmith8** [comment]
@tomastiminskas unsure how to test this?

**Comment by tomastiminskas** [comment]
@tomsmith8 not easy way. I think I'm the only one that can test it running the app from Xcode and using a tool that apple provides to check memory leaks. Let's keep this ticket open for now. I want to spend some more time on this when I have some free time just to double check the new changes didn't cause new memory leaks

**Comment by rodhan** [comment]
Please assign this to me too @tomsmith8 as it is part of https://community.sphinx.chat/bounty/958

**Comment by tomastiminskas** [comment]
@rodhan as it says in the ticket please use `test-flight` branch as the base branch on any iOS or Mac task. Master represents the version we had in the App Store before we were blocked from there, so it's an old version of the app. Also feel free to send me a message in Sphinx or email me at tomasalbertotiminskas@gmail.com if you need help or clarification on the code structure and the issues.

**Comment by rodhan** [comment]
Perfect thanks @tomastiminskas. I'll do that.
