### ISSUE TITLE
Error message improvements for failed messages

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#199]
**Task**

If a message fails, it often does _after_ the person leaves the conversation, so they have no way of knowing it failed.

**We should make improvements here**

If it does fail:
 - check to see if the conversation is in the active view and just show the current error notice
 - if they have left the conversation, show a popup (message failed) that shows for a few seconds and disappears?
 - show an error indicator next to the contact or tribe if the last msg activity in that conversation is a failed msg (this means it was not resent). The indicator can go away once the user views the failed msg even if they don’t resend it. We don’t want the error showing forever.

**Comment by tomsmith8** [comment]
@tomastiminskas failed messages are sometimes not known until going back on a conversation. Here are some ideas to improve that UX for users. Let me know if you have any other ideas too

**Comment by tomastiminskas** [comment]
@tomsmith8 I think for now the easiest way to improve this is show the message in red color and a error sign in the chats list. I will implement this on both iOS and Mac and we can see how it works and then get some feedback from Milan on the best way to show this to the user. What do you think?

Showing the error message and then remove it when the user enters the chat again would need some additional changes that I would need to think about, so I prefer to way with a simple way for now and then do improvements.

**Comment by tomsmith8** [comment]
@tomastiminskas Sure, I think thats a good start.
