### ISSUE TITLE
My desktop app stalled and I had to force quit.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-mac#213]
I clicked into a thread inside a tribe and then the desktop application froze. I had to force quit the app. 

I sent a report after I forcequit.

**Comment by ecurrencyhodler** [comment]
This randomly occurred again. I think it was just running in the background and stalled. I had to force quit.
https://github.com/stakwork/sphinx-mac/assets/32662508/6ef6f537-792b-421c-8ae0-8ef27f377397

**Comment by tomastiminskas** [comment]
Closing this since it seems related with the memory leaks we fixed. We can re open if it happens again
