### ISSUE TITLE
Button in SecondBrain isn't always clickable

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#217]
**Task**

Pressing the confirmation button 'Confirm' isn't always clickable on the Sphinx client (it works in the browser). We think the issue is happening as a layer above navfiber on the client side.

Loom (notice on the last attempt in the source table): [here](https://www.loom.com/share/78fa142a9ab144e9b3aecc1f2e4edda0?sid=922799c1-d04d-4471-b1cb-0eef988c01af)

Steps to recreate

- adding content flow and press confirm
- editing a topic name in the Topics area in the the source table and pressing confirm

**Acceptance Criteria**

- Buttons should be tappable everywhere on the component

**Comment by tomastiminskas** [comment]
I can check this too since I will be working on Mac app.

**Comment by tomastiminskas** [comment]
@tomsmith8 It's fixed. it will be included in next release going out today or tomorrow
