### ISSUE TITLE
Pressing `enter` on a highlighted user should autofill when tagging

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#224]
Use “test-flight” branch

**Task**

When tagging a user, pressing `enter` should autofill the selected user BUT not send the message:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/84142c98-3db8-42ab-965b-d5c0e2d63dc3)

This already works with `tab` but we should work for `enter`

**Acceptance Criteria**

- [ ] Use “test-flight” branch
- [ ] Pressing `enter` on a highlighted user should autofill

**Comment by tomsmith8** [comment]
Realised 'tab' does the same actually...

**Comment by aliraza556** [comment]
@tomsmith8 ould you please assign this task to me?

**Comment by tomsmith8** [comment]
@aliraza556 What is your Sphinx name? or pubkey?

**Comment by aliraza556** [comment]
My name is Ali Raza.
pubkey:    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJRg8pkb7X/UFMutIaLQoc89tQdaf5/O++Syl2xV/sja alirazaakhtar1122@gmail.com

**Comment by patgarner** [comment]
I would be happy to take this one

**Comment by patgarner** [comment]
If it's a pain in the butt to merge my changes from the pull request on this fork let me know. I'm happy to create a new fork and submit a pull request from there.
