### ISSUE TITLE
View transaction history on Mac desktop

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#232]
**Task**

We need to support viewing transaction history for desktop users.

**Design Options**

1. V1 - Add to menu list 'View Transactions'?

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/10c1ebab-7d1a-4c6f-a19d-d178487fe836)

2.  Add transaction icon in the UI somewhere?

**Design**

- Reuse components from mobile to display users transactions

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/d40e0af7-c168-4ddd-8acc-7ae602244495)

**Comment by tomsmith8** [comment]
@tomastiminskas Thoughts on easiest way to implement Trxn history for desktop. We're prioritising this as Bounty Hunters using desktop are unable to see if they have been paid

**Comment by tomastiminskas** [comment]
@tomsmith8 I think option 1 is easiest (adding item to open transactions on menu list). I will work on this today and I will try to have a version out with it by the end of the day

**Comment by tomsmith8** [comment]
Awesome thanks! We'll also need a similar approach for Windows
