### ISSUE TITLE
When clicking on a thread with a large initial message and image, the message gets cut off.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-mac#238]
When clicking on a thread with a large initial message and image, the message gets cut off. As you can see, the full body of the text isn't visible.  

<img width="655" alt="Screenshot 2023-11-22 at 12 05 48 PM" src="https://github.com/stakwork/sphinx-mac/assets/32662508/0eaa74f0-85cf-4b2e-acc8-79e43a8d8218">

We currently have the ability to click to expand the text box but even then the full message doesn't get displayed.

https://github.com/stakwork/sphinx-mac/assets/32662508/849ef04d-733f-4fd6-888e-f273656f3ed8

Enable the functionality where when a user clicks, they are able to view the whole text message. And if they click again, it rolls back up.

### Acceptance Criteria

- [ ] Test locally on your computer
- [ ] Post a video of the functionality in the PR

**Comment by sirajlekhak** [comment]
Is it still open ? Can I work on this ? @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Yes it is! We also have a bitcoin bounty for it as well. Are you interested? https://community.sphinx.chat/bounty/758

**Comment by yuvicc** [comment]
Sure!
I'll have a look

**Comment by ecurrencyhodler** [comment]
Welcome @i-am-yuvi. Awesome. Are you on sphinx chat and have you signed into our home page? https://community.sphinx.chat/bounties

If not I can help you get a code to sign up with sphinx chat.

**Comment by yuvicc** [comment]
Yes, I have signed up already!

**Comment by ecurrencyhodler** [comment]
okay great! What is your sphinx user name? I'll add you to the bounty.

**Comment by yuvicc** [comment]
Yuvraj Chhetri

**Comment by ecurrencyhodler** [comment]
Great! Also how did you hear about our project?

**Comment by yuvicc** [comment]
I heard about it from a friend!

**Comment by ecurrencyhodler** [comment]
@i-am-yuvi do you have an update on this issue?

**Comment by tomsmith8** [comment]
@ecurrencyhodler I'm unassigning this one

**Comment by Khaalid-oh** [comment]
@SAIF

**Comment by tomastiminskas** [comment]
It has been solved by adding a scroll view that allows to scroll and see the entire text when there's media content
