### ISSUE TITLE
Add Chinese and Japanese translations

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#239]
**Task**

Add and translate all the strings in the app (from different files) in Japanese and Chinese. This should be applied to `localizable.string` and also to all localized storyboards and xibs.

Potential solution:
- Find all storyboard and xib files that are localized
- create a file with all the strings
- translate them
-  finally create the new files for each language with the new translated string

**Acceptance Criteria**

- [ ] Add Japanese and Chinese translations

**Comment by wright-eric** [comment]
Hi @tomastiminskas is this still relevant and can i work on it? If yes then can you please assign it to me ?

**Comment by alejandrocordon** [comment]
I can try it
