### ISSUE TITLE
Polish web page load

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-mac#24]
When you first open up the Second Brain interface, you see this before the homescreen loads:
![Image](https://user-images.githubusercontent.com/104323003/203436123-abc1b31b-e0eb-4edc-99e2-d4a6fad655ee.png)

Let's get rid of that and have a nice simple loading spinner. Once we have a logo we can add it, but for now let's just make it look professional.

**Comment by jimBeaux27** [comment]
@soup20 @tomastiminskas fixed in https://github.com/stakwork/sphinx-mac/pull/78
