### ISSUE TITLE
Add ability to highlight specific words 

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#240]
**Task**

Allow to share code snippets on desktop using some special characters to delimitate code. Figma [Link](https://www.figma.com/file/L1oq8hh8kYU90bQxPAin3G/Mobile-Design-System---Dark-Version?type=design&node-id=7472%3A9345&mode=design&t=Nc0joYFntzsBCcGe-1)

Let's use one backtick at the start and end: `example`

Implement new collection view items to show formatted code in chats

**Design**

- Implement something similar to this:
- Colour #FF9900
<img width="583" alt="image" src="https://github.com/stakwork/sphinx-mac/assets/142233216/e252417a-5ed0-42bd-ab00-8b70b5e045e1">

**Comment by Antanasijevic** [comment]
![image](https://github.com/stakwork/sphinx-mac/assets/13258550/95d04a9e-3013-4b1f-bf2b-85674faf6d21)

**Comment by tomsmith8** [comment]
Yeah this is exactly how I imagined it!

**Comment by tomsmith8** [comment]
Would be great to have a Figma link for this

**Comment by Antanasijevic** [comment]
@tomsmith8 Sure, you can find final figma project here
https://www.figma.com/file/L1oq8hh8kYU90bQxPAin3G/Mobile-Design-System---Dark-Version?type=design&node-id=7472%3A9345&mode=design&t=Nc0joYFntzsBCcGe-1

**Comment by tomastiminskas** [comment]
@tomsmith8 I did a first implementation of this feature in both iOS and Mac. It is supported in chat messages, thread header and threads list. The design doesn't match exactly the Figma designs but it's pretty similar. Please help me testing this when new versions are out (uploading them right now)
