### ISSUE TITLE
Save who a user is replying to when changing chats

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#242]
Use “test-flight” branch

**Task**

As per this [Loom video](https://www.loom.com/share/9c3bcf81b0eb42e28cbb1882168a8d27?sid=1b57cc3d-67ea-4697-9828-7ec61af64b62), when replying to a thread and changing chats and going back, it doesn't save the state of the message I was replying to.

**Acceptance Criteria**

- [ ] Use “test-flight” branch
- [ ] When returning back to a chat with a threadI started to replying to, allow the user to still be replying to that user

**Comment by tomsmith8** [comment]
hey @SharkyBytes - Are you on Sphinx chat so I can assign you the bounty? https://community.sphinx.chat/bounties - If not, contact me at tomsmith@stakwork.com

**Comment by Khaalid-oh** [comment]
👍🏽
