### ISSUE TITLE
Split Auth and Set Budget

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#243]
**Task**

Split out Auth and Set Budget.

When opening secondbrain, we need to 'Authorise' the user (not set a budget):

Replace the url with secondbrain url:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/a0eec917-761b-4aea-8313-9caaa1c44cb9)

Set Budget:

https://www.figma.com/file/YuEbi4x32Mm8ZQJdnrs4uc/Second-Brain-Final-Designs?type=design&node-id=1372-13196&mode=design&t=U0ykLPaEYAspxcLr-4

**Comment by tomastiminskas** [comment]
Current flow:

### When performing a search or clicking on a trending topic:
- App receives message from SB through bridge with: 
     1. `type = AUTHORIZE`
     2. `application = Sphinx`
- App presents Authorize view
- User set budget on Authorize view field
- App sends message through bridge with: 
    1. `type = AUTHORIZE`
    2. `application = Sphinx`
    3. `budget = 100` (any budget amount)
    4. `pubkey = pubkey` (user pubkey)
    5. `password = password` (random 16 length string)
    
New flow
- App should receives message with `type = AUTHORIZE` from SB through bridge on web page load completes
- App sends same message but with no budget (SB should allow receiving the authorize message with no budget)
- When performing a search or any action SB should send a message with new type (something like `SETBUDGET`)
- Apps present new view to set budget
- Apps send message with new `type = SETBUDGET`, `application`, `budget` and any additional field you might need to verify identity (`password?, pubkey?`)

@tobi-bams let me know if this makes sense

**Comment by tomastiminskas** [comment]
@tobi-bams right now SB is re sending the AUTHORIZE message so the app can re authorize with more budget. In the new flow I guess SB should re send the SETBUDGET message so app can set more budget for actions

**Comment by tobi-bams** [comment]
Alright, thanks!!

**Comment by tomsmith8** [comment]
We've made it backwards compatible on Navfiber side. I think we're good to release the client apps side now.

@tomastiminskas @tobi-bams

**Comment by tomastiminskas** [comment]
@tomsmith8 I have the PRs ready on iOS and Mac so if @tobi-bams confirms we are ok to go, then I will release internal testing version today for both
