### ISSUE TITLE
Unable to see messages upon initialization until I click

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-mac#256]
When I first bring up sphinx chat, I have to click a message or tribe in order to see messages.

https://github.com/stakwork/sphinx-mac/assets/32662508/9151bda1-5986-4960-a232-d4e51e61c60d

IMO the chat should show messages in the top message or top tribe by default.

**Comment by tomastiminskas** [comment]
@ecurrencyhodler I will apply this on next release. Basically it will still show empty chat when launching the app for the first time with the update, but starting from there it will keep a reference of the last open chat so next time you launch sphinx it will default to it

**Comment by ecurrencyhodler** [comment]
Thanks tom!!
