### ISSUE TITLE
Scroll bar persists in tribes

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-mac#258]
The scroll bar which (I think) should be displayed only in the friends bar is also displayed in the tribes column. Not only that, it persists when I scroll up and down. We should remove that when I'm scrolling up and down and looking at various tribes.

https://github.com/stakwork/sphinx-mac/assets/32662508/457f5cb5-bea2-434c-90b0-912cef448a25

**Comment by tomsmith8** [comment]
Combined into one ticket here as related: https://github.com/stakwork/sphinx-mac/issues/257
