### ISSUE TITLE
Add the ability to set a users Tip amount in Mac

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#267]
Use “test-flight” branch

See iOS implementation on updating the value on Profile. It’s calling “updateTipAmount” on UserContact+CoreDataClass which uses the updateUser endpoint (PUT /contacts/\(id)) to update the tip amount on our backend (Relay).

https://github.com/stakwork/sphinx-ios/blob/08dd341bfcf6793b31350d38b0f24f498de6d0c0/sphinx/Core%20Data/UserContact/UserContact%2BCoreDataClass.swift#L437

**Task**

- Add same functionality to Mac
- Reuse same design as iOS (Above the meeting server)

UI on iOS as per this image:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/ad4f2572-3939-4f1c-bdaa-a027b9a9bb51)

We can add it to the same place above Meeting Server for Mac:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/bb95a052-f754-47e8-af08-ca9e5f5c9c74)

**Acceptance Criteria**

- [ ] Use “test-flight” branch
- [ ] Add ability to set default tip amount on Mac

**Comment by patgarner** [comment]
Hey, this is a follow up comment after messaging on Sphinx about working on this issue.

**Comment by tomsmith8** [comment]
Assigned @patgarner !

**Comment by ecurrencyhodler** [comment]
@patgarner how's this issue coming along?

**Comment by patgarner** [comment]
@ecurrencyhodler with any luck I'll have something for this today or tomorrow at the latest.

**Comment by patgarner** [comment]
I've created a pull request for my changes implementing this feature, however, combined with other existing changes it's a heavy request. Should I submit my changes differently?

**Comment by tomastiminskas** [comment]
@patgarner thanks. It was a heavy request because you set the base branch on master, but I just changed it to test-flight and now it's ok. I will review during the day and give you some feedback

**Comment by patgarner** [comment]
@tomastiminskas Ah, I see! My bad, thanks for fixing it! Good deal.
