### ISSUE TITLE
Deleting a tribe crashes desktop

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#281]

**Comment by tomsmith8** [comment]
cc @Analysislearning

**Comment by Analysislearning** [comment]
The issue is not happening anymore. 
I tried on desktop (MAC). The app doesnt crash.

Check video. 
https://github.com/stakwork/sphinx-mac/assets/149190792/dda7a1a7-5c6f-41a6-ac88-8d7b00b67223
