### ISSUE TITLE
Timestamp issue with HMAC key being in the future

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#282]
Logged into Windows via VM and my timezone was technically in the future. This messed up the HMAC timestamp for other clients as they we always 'old' and therefore could never log in properly.

- I have an infinite loading spinning on mac
- I have orange bolt on iOS

**Steps**

- Opened Sphinx on Windows
- Now iOS and Mac won't work

**Comment by tomsmith8** [comment]
@tomastiminskas @Evanfeenstra 

Hey both, after trying to test your newest build on Windows, it seems to have messed up my mac/ios keys.

Unable to load anything and have the infinite spinner (It may cause lots of requests to relay again)

**Comment by tomastiminskas** [comment]
@tomsmith8 I will spend some time trying to recreate on my side. Good to know that it happens when using Windows app. There might be an issue somewhere on the Windows app causing it. I would suggest to uninstall and restore account on iOS and Mac after closing Windows app. Let me know please if that works

**Comment by tomsmith8** [comment]
My restore is stuck on 1% for Mac:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/cd32c3ee-bee3-452e-a2fa-9e98a91b9a0e)

I wonder if hmac key is the issue and there is a race condition causing Windows to take prio and iOS/Mac not

**Comment by tomastiminskas** [comment]
If you closed the Windows app, then it shouldn't affect Mac/iOS when restoring. Unless proxy server is overwhelmed and it can't respond to requests. Did you close all apps before trying to restore on Mac?

**Comment by tomastiminskas** [comment]
@tomsmith8 still not able to restore account? I tries with my proxy test account and I could even when some requests fail. Send me you WhatsApp if you have so we ca talk there and try to figure this out. You can send it to my email tomasalbertotiminskas@gmail.com
