### ISSUE TITLE
Add Second Brain Icon to Sphinx Apps bar

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#311]
**Task**

A new Icon for Secondbrain. 

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/8f6e5ac2-512f-414f-a295-4dd240c48fc2)

- Graph/brain style
- If it could be animated (spin) that would be awesome

**Comment by Antanasijevic** [comment]
@tomsmith8 You can download Second Brain Icon in SVG format on this link. Lets use static image until i come up with something animated. Maybe we can move Animated alternative to this icon into separate ticket?

https://drive.google.com/file/d/1xon3Ao4fqpnS0fJlXcQWIeqK8r0KP-Tp/view?usp=sharing
