### ISSUE TITLE
Add 'SecondBrain URL' field to tribe settings modal

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#312]
**Task**

Add a new field to Tribe Settings called `SecondBrain URL`

- New field in Tribes schema called `second_brain_url`
- Add new input field to paste in a URL

<img width="415" alt="image" src="https://github.com/stakwork/sphinx-mac/assets/142233216/d07468cd-2f1b-4aa9-ba9d-b44d1736a774">

**Acceptance Criteria**

- [ ] Add new field to Tribe Settings called `Second Brain URL`
- [ ] Variable in schema to use is `second_brain_url`

**Comment by Khaalid-oh** [comment]
@Saif

**Comment by tomastiminskas** [comment]
@tomsmith8 I'm testing the changes @Khaalid-oh did for this but it seems the server is not prepared to handle this. The cause of the issue could be in 2 different places:
- Tribes server not handling this new param as it should
- Relay server not handling it as it should (create and edit Group endpoints are relay endpoints that then hit tribes server endpoint to create/update the tribe). So maybe relay changes were not done yet or my relay is not deployed with the new changes. 

Without those changes ready and deployed to my node I can't really test this out
Any idea on what's the state of the server side changes for this?

**Comment by tomsmith8** [comment]
Let me check in with @tobi-bams for this and get back to you

**Comment by tobi-bams** [comment]
@tomastiminskas please which node are using to test, so I can deploy the latest relay change?

**Comment by tomastiminskas** [comment]
@tobi-bams it's my main node. Public key: 027dbce35947a3dafc826de411d97990e9b16e78512d1a9e70e87dcc788c2631db

Let me know when it's deployed please

**Comment by tomastiminskas** [comment]
@tobi-bams I was testing this on my main node and it worked great. But while testing I found a bug that seems to be old. So as now we have a new field for `second_brain_url`, I tried to reset the `app_url`of my tribe to an empty value and it seems the update doesn't work. I debug the params being sent to my relay and I'm actually sending `""` (empty string) for `app_url`, but when I get tribe info back from tribes server it comes with the old value again. 

Not sure if the issue is on relay or tribes server but something is preventing the app to set en empty value for that field

**Comment by tobi-bams** [comment]
> @tobi-bams I was testing this on my main node and it worked great. But while testing I found a bug that seems to be old. So as now we have a new field for `second_brain_url`, I tried to reset the `app_url`of my tribe to an empty value and it seems the update doesn't work. I debug the params being sent to my relay and I'm actually sending `""` (empty string) for `app_url`, but when I get tribe info back from tribes server it comes with the old value again.
> 
> Not sure if the issue is on relay or tribes server but something is preventing the app to set en empty value for that field

Hmmmmmm....

I guess this is a relay issue, lemme take a look.

**Comment by tomastiminskas** [comment]
@tobi-bams any update on this? Also once it's fixed and tested let's deploy this fix and the `second_brain_url` addition to all nodes including proxy so I can release a version with the changes

**Comment by tomsmith8** [comment]
@Evanfeenstra - Tobi is off today and tomorrow, reckon you could pick this small change up?

This is the issue @tomastiminskas is talking about:

> as now we have a new field for `second_brain_url`, I tried to reset the `app_url`of my tribe to an empty value and it seems the update doesn't work. I debug the params being sent to my relay and I'm actually sending `""` (empty string) for `app_url`, but when I get tribe info back from tribes server it comes with the old value again.
> 
> Not sure if the issue is on relay or tribes server but something is preventing the app to set en empty value for that field

**Comment by tomsmith8** [comment]
@Evanfeenstra nevermind, Tobi has a fix for this already!

**Comment by tobi-bams** [comment]
@Evanfeenstra please can you help review this PR: https://github.com/stakwork/sphinx-relay/pull/808

**Comment by tobi-bams** [comment]
@Evanfeenstra currently, the tribe server does not store an empty string when it's passed from the client. 

Please can we ensure the tribe server stores an empty when `app_url`, `feed_url` or `second_url` is passed as an empty string

**Comment by tomsmith8** [comment]
Thanks @tobi-bams 

@Evanfeenstra I think Raphael is off too. Reckon you could make the change above to the tribes server?

**Comment by tomsmith8** [comment]
Ok, If we can update Relay, we can test this. If it cannot set the string to being empty we'll have to make the additional change on the tribes Server.

@Evanfeenstra Could you update relay so Tom T can test this?
