### ISSUE TITLE
Strange formatting for Auth screen

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#318]
**Task**

Strange formatting for Auth screen for secondbrain since newest mac version:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/dcecce77-6a0e-4cfb-a2af-d2a622fd5855)

**Comment by tomastiminskas** [comment]
@tomsmith8 I will take a look. It's definitely related with Material Icons font. Not sure why it's not recognized but should be able to fix it easily and upload a new release

**Comment by tomastiminskas** [comment]
@tomsmith8 Uploading a new version now with fixes for this and other fixes related with joining jitsi calls from universal links
