### ISSUE TITLE
Threads cuts of message with new backticks highlight feature

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#338]
**Task**

Current view:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/b283ee7b-2cfb-446c-ba17-021a6bbd496e)

Actual message:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/1fa9ab31-d303-4bd5-9a99-6a6fdf82682e)

**Acceptance Criteria**

- [ ] Fix issue where msg gets cut off in threads view where highlight is used

**Comment by tomsmith8** [comment]
@tomastiminskas pretty sure the issue is related to `highlight` but not 100%. if so, we can bounty the fix?

**Comment by Khaalid-oh** [comment]
Can you assign this to me ?

**Comment by tomastiminskas** [comment]
@Khaalid-oh it's related with some changes I did recently and should be an easy fix so I will take it

**Comment by tomastiminskas** [comment]
@tomsmith8 new version going out soon with this fixed
