### ISSUE TITLE
Jitsi - automatically takes mic off mute

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#341]
Browser - chrome

- User A joins and mutes
- User B joins
- User A's mic unmutes automatically

https://www.loom.com/share/99262a55de484b97a7b0b7bd894f0e55?sid=cc3c02e2-49a3-4b03-ad77-e033663c3c9b

**Comment by tomsmith8** [comment]
@tomastiminskas @gonzaloaune 

Placing this issue in this repo as thats where Paul & I have experience but also in browser.

If you join a Jitsi call, mute yourself and then someone joins, it automatically unmutes you. I guess this is some kind of server side setting?

**Comment by gonzaloaune** [comment]
@tomsmith8 this should be resolved now, can you confirm? I tested with Tom and looked ok to us.

**Comment by tomsmith8** [comment]
Fixed for me now too. What do you do?

**Comment by gonzaloaune** [comment]
Changed this file:

```
sudo vi /etc/jitsi/meet/jitsi.sphinx.chat-config.js
```

Changes were `startWithAudioMuted` to `true` and `startAudioMuted` to `0`

**Comment by tomsmith8** [comment]
hm, this seems to automatically mute everyone when joining now.

Ideally this wouldn't be the case. The bug was when the user starts on mutes it automatically unmutes. Not sure how we can solve that?

**Comment by gonzaloaune** [comment]
@tomsmith8 this has been fixed by allowing the first 2 on the call to be unmuted but subsequent users will be muted by default.
