### ISSUE TITLE
Right panel navigation changes

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#342]
All the chat secondary views will now show in a right panel instead of showing as new windows. Similar to how we show the podcast player on tribes with a podcast. This will apply to the following views:

- Tribe details / Share Tribe QR code / Edit Tribe
- Contact Details / Contact Public key QR code
- Threads list
- Thread view
- Podcast player (already implemented)

Using the model of the `NewPodcastPlayerViewController` which is presented as a child view controller on the `podcastPlayerView`, build the infrastructure to present any view controller on the right panel of the `NewChatViewController` using a new container view. This infrastructure needs to be built so any view controller can be presented there, without linking them yet.

The container view and any needed layout changes need to be built in the storyboard to be consistent on how the app is built (instead of building the UI elements on the code)

The presentation of the right panel needs to be animated from right to left. 

Right panel width must be customizable

Screenshot reference: all screenshots are descriptive. Final designs needs to be taken from Figma

---
<img width="722" alt="Right-Panel" src="https://github.com/stakwork/sphinx-mac/assets/2242281/338f3a17-9f21-44c1-afca-708582083423">

---

**_Base branch: test-flight_**

Figma instructions: https://github.com/stakwork/sphinx-ios/issues/435
Designs: https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3378-20203&mode=design&t=R0sd1AU3jobTYMGR-0

**Comment by Khaalid-oh** [comment]
Can you assign this to me ?

**Comment by tomsmith8** [comment]
@tomastiminskas we good to go one this one?

**Comment by tomastiminskas** [comment]
Yes, we should be good to go @tomsmith8

**Comment by tomastiminskas** [comment]
@tomsmith8 opening this again so I can track it in Sphinx App GitHub project until we finish testing it!
