### ISSUE TITLE
Main views navigation changes / over dashboard

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#343]
Additional views like Profile, Transactions, Create Tribe or Add Contact will now show up over the dashboard in the same window instead of showing as new windows popping up.

This will apply to the following views:
- Profile
- Transactions
- Create Tribe
- Add new Contact

The view controllers listed above will show as child view controllers inside a container view over a blurred background that will cover the entire dashboard main windows (as shown in the screenshot). This infrastructure needs to be built so any view controller can be presented there, without linking them yet.

The container view and any needed layout changes need to be built in the storyboard to be consistent on how the app is built (instead of building the UI elements on the code)

Container view width must be customizable

The presentation of the right panel needs to be animated with a fade in / fade out.

Screenshot reference: all screenshots are descriptive. Final designs needs to be taken from Figma

---

<img width="723" alt="Main-Views" src="https://github.com/stakwork/sphinx-mac/assets/2242281/4a0e8f2b-a7f6-4fd9-8a9d-98236dbfe9f1">

---
**_Base branch: test-flight_**

Figma instructions: https://github.com/stakwork/sphinx-ios/issues/435
Designs: https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3435-26914&mode=design&t=R0sd1AU3jobTYMGR-0

**Comment by Khaalid-oh** [comment]
@Saif
