### ISSUE TITLE
Chats list header and new dropdown Menu

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#344]
Build the UI of the new chats list header and the new dropdown menu to access additional views.

<img width="750" alt="Screenshot 2024-04-04 at 16 24 17" src="https://github.com/stakwork/sphinx-mac/assets/2242281/d57dcd14-a503-42cd-909e-8096afa504ec">

---

Header layouts: 

<img width="183" alt="Header" src="https://github.com/stakwork/sphinx-mac/assets/2242281/c4dcea20-e3c1-4f7b-9b5f-a78d0e0b3eef">

---

Menu layouts: 

<img width="166" alt="Menu" src="https://github.com/stakwork/sphinx-mac/assets/2242281/bd6969cb-75c5-480b-afe7-793b56a57326">

---

All views needs to be built in storyboard or xibs to be consistent with how the project is built (instead of building them on the code)

**_Base branch: test-flight_**

**Figma instructions: https://github.com/stakwork/sphinx-ios/issues/435**
**Designs: https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3512-27733&mode=design&t=OcJcpmQ7uMhPq5Q5-0**

**Comment by Khaalid-oh** [comment]
I can help with this

**Comment by tomastiminskas** [comment]
@Khaalid-oh I just adapted the ticket with Figma designs link and a link to Figma instructions. 

On any case let's wait for @tomsmith8 to assigned ticket and bounty to you and then you can start working on it

**Comment by Khaalid-oh** [comment]
Alright, thanks T

**Comment by tomsmith8** [comment]
@Antanasijevic Do you have the Figma file for this one?

**Comment by tomastiminskas** [comment]
@tomsmith8 I think this is the link: https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3512-27733&mode=design&t=OcJcpmQ7uMhPq5Q5-0

**Comment by tomsmith8** [comment]
Thanks @tomastiminskas !

@Khaalid-oh here ya go ^^
