### ISSUE TITLE
New navigation for Contact Details / Share Public Key QR

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#346]
Present the following views in the right panel of the chat view:

- Contact Details
- Share Public Key QR

**_Base branch: test-flight_**

Screenshot references: all screenshots are descriptive. Final designs needs to be taken from Figma

---
Contact Details

<img width="722" alt="Contact-Detail" src="https://github.com/stakwork/sphinx-mac/assets/2242281/4f1dc919-36bf-40a0-8ee0-b781b1f8877f">

---
Share Public Key QR

<img width="722" alt="Share-Public-Key" src="https://github.com/stakwork/sphinx-mac/assets/2242281/f18586af-dd95-4679-8f28-020aabf49c5b">

---
First time a view is presented on the right panel it should expand animated from right to left. When switching from one view to the other inside the right panel it should animate with a fade in / fade out animation. When closing panel it should animate from left ro right. 

Based on Figma designs view header needs to be re built. The views themselves should keep the same design as they have now.

Figma instructions: https://github.com/stakwork/sphinx-ios/issues/435
Designs: https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3378-20203&mode=design&t=R0sd1AU3jobTYMGR-0

**Comment by Khaalid-oh** [comment]
@Saif

**Comment by tomastiminskas** [comment]
@tomsmith8 opening this again so I can track it in Sphinx App GitHub project until we finish testing it!
