### ISSUE TITLE
New navigation for Transactions view

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#348]
Present Transactions on new view on top of the dashboard

**_Base branch: test-flight_**

Screenshot references: all screenshots are descriptive. Final designs needs to be taken from Figma

---

<img width="723" alt="Transactions" src="https://github.com/stakwork/sphinx-mac/assets/2242281/b5884cf5-49e0-4cf0-9847-fcfc79cbeead">

---

All animations in this new presentation view should use a fede in / fade out animation

Based on Figma designs view header needs to be re built. The Transactions view itself should keep the same design as it has now.

Figma instructions: https://github.com/stakwork/sphinx-ios/issues/435
Designs: https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3435-26914&mode=design&t=R0sd1AU3jobTYMGR-0

**Comment by Khaalid-oh** [comment]
@Saif
