### ISSUE TITLE
Chat view, retain scroll on last viewed msg

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-mac#35]
This issue also applies to sphinx-ios.

To recreate the state of the problem:
 - view any chat
 - scroll back a few pages to see an older message
 - leave the chat and return to it
 - the chat view is reset to the most recent message (even if no new message comes in)

A better experience is common in Discord and other views:
 - always return to the last point viewed in the conversation even if a new message comes in
 - indicate a new message is available (already implemented) and scroll to the bottom when the new message icon is tapped

**Comment by jimBeaux27** [comment]
@tomastiminskas working on this right now

**Comment by jimBeaux27** [comment]
Starting with iOS b/c it's slightly easier then will port over to mac: https://github.com/stakwork/sphinx-ios/pull/143

**Comment by jimBeaux27** [comment]
Addressing on https://github.com/stakwork/sphinx-mac/tree/jc/develop/retain-chat-scroll
