### ISSUE TITLE
New navigation for New Contact views

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#350]
Present New Contact views on the new view on top of the dashboard

- Add Friend
- New to Sphinx
- Already on Sphinx

**_Base branch: test-flight_**

Screenshot references: all screenshots are descriptive. Final designs needs to be taken from Figma

---

<img width="723" alt="Add-Contact" src="https://github.com/stakwork/sphinx-mac/assets/2242281/2ae98cc8-d44a-4416-807d-f49999f29f0c">

---

All animations in this new presentation view should use a fede in / fade out animation

Based on Figma designs view header needs to be re built. The New Contact views should keep the same design as they have now.

Figma instructions: https://github.com/stakwork/sphinx-ios/issues/435
Designs: https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3435-26914&mode=design&t=R0sd1AU3jobTYMGR-0

**Comment by Khaalid-oh** [comment]
Can you assign this @Saif?
