### ISSUE TITLE
New navigation for Threads list and Thread view

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#351]
Present the following views in the right panel of the chat view:

- Threads List
- Thread View

**_Base branch: test-flight_**

Screenshot references: all screenshots are descriptive. Final designs needs to be taken from Figma

---
Threads List

<img width="722" alt="Threads" src="https://github.com/stakwork/sphinx-mac/assets/2242281/0d69de66-6e0e-4e18-9e83-3df1466f2221">

---
Thread View

<img width="722" alt="thread" src="https://github.com/stakwork/sphinx-mac/assets/2242281/6040e1e1-f123-48a1-8a63-a05068753141">

---
First time a view is presented on the right panel it should expand animated from right to left. When switching from one view to the other inside the right panel it should animate with a fade in / fade out animation. When closing panel it should animate from left ro right. 

Based on Figma designs view header needs to be re built. The views themselves should keep the same design as they have now.

Figma instructions: https://github.com/stakwork/sphinx-ios/issues/435
Designs: https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3378-20203&mode=design&t=R0sd1AU3jobTYMGR-0

**Comment by Khaalid-oh** [comment]
Can you assign this to me?

**Comment by tomastiminskas** [comment]
@Khaalid-oh before working on any of these tickets you asked for assignment, we should have done these 2 in which the rest depends on:

https://github.com/stakwork/sphinx-mac/issues/342
https://github.com/stakwork/sphinx-mac/issues/343

You could take them if you want, but let's wait @tomsmith8 to confirm. We still need to provide access to Figma project to get the designs details

**Comment by tomsmith8** [comment]
Yeah, these two can be picked up and are required for the remainingg tickets.

Here is the Figma Link to project [here](https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3378-20203&mode=design&t=AWuHStaRtxtaVkj6-0)

However, we haven't solved the dev-tools issues yet for developer access

**Comment by Khaalid-oh** [comment]
> Alright, thanks

**Comment by tomsmith8** [comment]
@Khaalid-oh can you comment on both and I'll assign

**Comment by Khaalid-oh** [comment]
Alright

**Comment by tomastiminskas** [comment]
@tomsmith8 opening this again so I can track it in Sphinx App GitHub project until we finish testing it!

**Comment by tomsmith8** [comment]
Woops, sorry Tom!

**Comment by tomastiminskas** [comment]
@tomsmith8 no problem Tom. Just want to track all the navigation changes we assigned to hunters on the project board in case Milan asked for new changes. I moved all to IN REVIEW now so we can keep testing for a while until we closed them. And I can't add them to IN REVIEW if they are closed
