### ISSUE TITLE
Tribe Member section

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#365]
Build new view for TRIBE MEMBERS in the right panel of the chat view

**_Base branch: test-flight_**

## General requirements
On Tribe details view a new option should be added `Tribe Members` in the 3 dots tribe menu only if you are the admin of the tribe (see screenshots below)

--------------------
<img width="1367" alt="Screenshot 2024-04-24 at 2 15 05 PM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/e801f5c4-688b-4b69-8128-683e34ee326a">
<img width="449" alt="Screenshot 2024-04-24 at 2 15 14 PM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/01753232-8139-4337-b16a-97c904be47ba">

--------------------

Tapping on this new option a new View Controller should be presented in the right panel on the same way Tribe Join Link is presented, that means showing the title and a BACK ARROW at the top to navigate back to Tribe Details view (see screenshot below)

--------------------

<img width="449" alt="Screenshot 2024-04-24 at 2 15 22 PM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/d837aa0e-122e-4b0e-96c5-afb65fdc1fd3">

--------------------
## New view requirements
- Title: Tribe Members (should be localized in string localized files)
- Back arrow: should navigate back to Tribe details as on Tribe Join Link QR code view
- Rows: design can be taken from iOS (`GroupContactTableViewCell.xib / GroupContactTableViewCell.swift`): https://github.com/stakwork/sphinx-ios/blob/test-flight/sphinx/Scenes/Groups/View%20Cells/GroupContactCollectionViewCell.xib
- Members list should look like iOS where initials will show up on the first member with that initial (see screenshot below)
--------------------
![IMG_6231](https://github.com/stakwork/sphinx-mac/assets/2242281/75f24d2d-36da-45ab-bc01-1c6814447ab8)
--------------------
- Logic and endpoint to get tribe members from relay can be taken from iOS: https://github.com/stakwork/sphinx-ios/blob/test-flight/sphinx/Scenes/Groups/Data%20Sources/GroupMembersDataSource.swift

**Comment by Khaalid-oh** [comment]
Can you assign this to me?

**Comment by tomastiminskas** [comment]
@Khaalid-oh what's you user on Bounties site?

**Comment by Khaalid-oh** [comment]
> @Khaalid-oh what's you user on Bounties site?

@Saif
