### ISSUE TITLE
Sphinx Desktop - Message input Bar

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-mac#381]
Finalize entire message bar layout nased on this concept 
https://github.com/stakwork/sphinx/issues/283

**Comment by Antanasijevic** [comment]
@tomastiminskas  In this concept i tried to cover all scenarios i could think of.
- Short and long messages
- Short and long Messages with attachment, one and multiple (up to 10) attachments, 
- Paid messages for all variations
- Drag and Drop attachment 
- Having double input bar (in chat and in thread next to it)
- Gif and Emoji dialog

https://github.com/stakwork/sphinx-mac/assets/13258550/34fde18b-d294-409e-81cc-f6909ec66272

**Comment by tomastiminskas** [comment]
@Antanasijevic they all look great. I would say we should separate this into 4 tasks:
- General redesign of bottom bar
- Redesign of attachments preview (up to 10)
- Logic to send multiple attachments 
- New icons on top bar

If you can prepare the designs in Figma I will go ahead and create tickets/bounties for them. It would be great if we can have a page in Figma with bottom bar redesigns without the attachments previews (so user taking the first task doesn't get confused) and a second one with multiple attachments preview designs. Also it would be great if you can show all states in the designs like: short text message, long multiline text message, message price active (after pressing in add price button), etc

We can discuss tomorrow morning if needed

**Comment by Antanasijevic** [comment]
@tomastiminskas Here is final layout for General redesign of bottom bar. Please let me know if you want us to go through assets.
Layouts for attachment preview will be moved to separate ticket, as discussed.

Figma Project
https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4242%3A135730&t=tef8LJ0ok5bm3u4g-1


Prototype
https://www.figma.com/proto/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4252-25997&t=XLPtO9cCnva4Jxax-1&scaling=min-zoom&page-id=4242%3A135730&starting-point-node-id=4252%3A25997&show-proto-sidebar=1

Video Preview



https://github.com/stakwork/sphinx-mac/assets/13258550/335267aa-8028-457f-8316-2299d1b0eda8

**Comment by Antanasijevic** [comment]
Designs for Redesign of attachments preview are moved to separate ticket #385
