### ISSUE TITLE
Bottom Bar redesign - Message Field container view

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#389]
Adapt exiting UI to the new designs on the message field container view. Existing UI is built based on expansion/collapse requirements (like moving chat view up when entered text is large/multiline, price view becoming wider as price is entered reducing width of input text field, etc) so it's recommended to adapt existing views to new designs instead of building UI from scratch. 

**_Base branch: test-flight_**

## General requirements
- All assets needs to be taken from Figma (export in 3x and create them adding versions for 1x, 2x and 3x in Assets section of the project)
- All colors need to be taken from Figma (some of them already exists in the project, some others need to be created). All new colors need to be created for both dark and light mode in the Color section of the app
- All sizes, margins, etc need to be taken from Figma.
- 
**Acceptance Criteria**

- [ ] Apply all designs with right sizes, colors and assets for both dark and light mode
- [ ] Record a video with loom for review when task is completed

**_Designs video: https://github.com/stakwork/sphinx-mac/assets/13258550/335267aa-8028-457f-8316-2299d1b0eda8_**
**_Design prototype: https://www.figma.com/proto/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4252-25997&t=XLPtO9cCnva4Jxax-1&scaling=min-zoom&page-id=4242%3A135730&starting-point-node-id=4252%3A25997&show-proto-sidebar=1_**
**_Figma designs: https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4242-135730&t=z4I07OL9PbmdiBB5-0_**

### 1. Bottom bar default elements

<img width="703" alt="Screenshot 2024-05-16 at 10 23 12 AM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/ceff8314-6985-489a-8b3a-c897ab747d85">

- Background color of the bottom bar changes matching the background color of the chat view
- Plus button stays on left side with different color, size and asset
- Gif and Emoji buttons are moved to right with different color, size and asset
- Plus, Gif and Emoji buttons are now inside the box of the input field

------------------------------------------
### 2. Entered text state

<img width="604" alt="Screenshot 2024-05-16 at 10 23 25 AM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/dbb2a2cf-e27a-4344-8e87-63ea50d846c1">

When text is entered in the message field:
- Font and size changes

------------------------------------------
### 3. Entered multiline text state

<img width="606" alt="Screenshot 2024-05-16 at 10 23 33 AM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/26a1271c-8cfa-44fd-89cb-cd7d1e4ac80a">

When text entered in the message field becomes multiline:
- Plus, Gif and Emoji buttons stay aligned to top inside the field box

**Comment by Khaalid-oh** [comment]
I can help
