### ISSUE TITLE
New Contact - Contact list Waiting state 

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-mac#394]
We need a state in contact list of invited person (for invites where you have a code to share. )
You just need to wait for the other contact to be online. 

User can open a empty chat, that contains information of the status (waiting for other person to show up online).
During this state messaging is not possible

Possible solution: It can be same a normal contact but with a “Waiting…” label in the second line. And maybe an overlay on the image/initials circle

**Comment by Antanasijevic** [comment]
@tomastiminskas Here is one simple option. One question - Can this type of chat be opened?

https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4405%3A144178&t=RYSEYU37HvCo4x9h-1

**Comment by Antanasijevic** [comment]
@tomastiminskas One example of pending contact with chat window opened.
We can use an empty state of the chat to give more detail about pending state.
Text used here is just a placeholder. We can discuss proper wording.

![image](https://github.com/stakwork/sphinx-mac/assets/13258550/94ffc637-8afc-4a9b-9f6d-1a0ecd8f2e5a)

**Comment by Antanasijevic** [comment]
@tomastiminskas  In addition to empty chat for waiting contact,
here is one of the old suggestion for empty chat of standard contact.
Something like this is pretty standard in all chat apps and i guess it may be a nice addition for us too.
It also provides a nice opportunity to explain encrypted nature of the messages


![image](https://github.com/stakwork/sphinx-mac/assets/13258550/2be5c86e-5777-4cc1-8f30-c5a7aa7398dc)

**Comment by Antanasijevic** [comment]
@tomastiminskas  Here are samples of chat in Waiting state and Empty (connected) state.
For consistency purpose, Should we have an empty state for pending also? (one with a barcode)

Waiting - Empty state
![image](https://github.com/stakwork/sphinx-mac/assets/13258550/a062b649-4fa5-4f88-ab16-04e84e3d7392)

Empty Chat
![image](https://github.com/stakwork/sphinx-mac/assets/13258550/0abc864b-d1d8-4120-8e7f-c88fe4619e59)

**Comment by tomastiminskas** [comment]
@Antanasijevic this looks great. I don't think we need an empty state for invite since we are not allowing to access the chat view from an invite row. At that moment you created the invite but there's no account in the other side so it doesn't make sense to even show a chat
