### ISSUE TITLE
Mentions autocomplete view redesigns

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#398]
Apply the new designs of the mentions autocomplete view. The view should show horizontally aligned with the cursor position as shown on the designs. It should adapt its height to mentions count if they are less than 3 and scroll if they are more than 3. In addition it should allow to navigate with keyboard arrows and mouse as in the existing designs. 

**_Base branch: test-flight_**

## General requirements
- All **assets** needs to be taken from Figma (export in 3x and create them adding versions for 1x, 2x and 3x in Assets section of the project)
- All colors need to be taken from Figma (some of them already exist in the project, some others need to be created). All new colors need to be created for both **dark and light** mode in the Color section of the app
- All **sizes, margins**, etc need to be taken from Figma.
-  **Navigation** should be allowed with keyboard arrow keys and mouse

**Acceptance Criteria**

- [ ] Apply all designs with right sizes, colors and assets for both dark and light mode
- [ ] Record a video with loom for review when task is completed

**_Figma designs: https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4481-165005&t=djNzMwzmszKH0KiD-0_**

## Screenshot reference

<img width="582" alt="Screenshot 2024-05-24 at 1 56 47 PM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/1e841c91-ec07-451d-8e5a-3a315082b037">

**Comment by Khaalid-oh** [comment]
Yeah, I can help with the pls
