### ISSUE TITLE
Jitsi Voice/Video In App for Mac Desktop

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-mac#40]
Currently our Mac desktop app opens a link to the browser to initiate a call.
 In our mobile apps we use the jitsi SDK to do voice/video calls native to the app. We want to use the Jitsi SDKs to bring the Mac Desktop app to parity with the mobile apps:

Ability to initiate either a voice or video + voice call from a chat
Make that call occur and stay within the Kotlin app
Example UI from iOS:
![IMG_3817](https://user-images.githubusercontent.com/96802642/220156162-cd02c500-0091-4798-aed3-b6fdcbd299ee.PNG)

(Android docs: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk/ )
(iOS docs: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk )
(Sphinx iOS Repo: https://github.com/stakwork/sphinx-ios/tree/test-flight )

**Comment by tomastiminskas** [comment]
I will close this since we are now opening calls in webview inside Mac app
