### ISSUE TITLE
Reply layout adjustments

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-mac#400]
Modify reply layout to better match new message bar

**Comment by Antanasijevic** [comment]
@tomastiminskas For V1 i suggest we go with simple adjustments like this.
We can discuss more advanced options in separate ticket

https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4528-34548&t=168XUsAZA1rzEWEl-1

**Comment by tomastiminskas** [comment]
@Antanasijevic looks great to me. We can bounty this out! Thanks
