### ISSUE TITLE
Reply bar redesign

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#402]
Apply the new designs of the reply view on bottom bar

**_Base branch: test-flight_**

## General requirements
- All **assets** needs to be taken from Figma (export in 3x and create them adding versions for 1x, 2x and 3x in Assets section of the project)
- All colors need to be taken from Figma (some of them already exist in the project, some others need to be created). All new colors need to be created for both **dark and light** mode in the Color section of the app
- All **sizes, margins**, etc need to be taken from Figma.
- Add "Replying to" before the sender of the original message localized to all supported languages (as it's shown in the designs)

**Acceptance Criteria**

- [ ] Apply all designs with right sizes, colors and assets for both dark and light mode
- [ ] Record a video with loom for review when task is completed

[**_Figma designs: https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4481-165005&t=djNzMwzmszKH0KiD-0_**](https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4528-34548&t=KpE7Qk14BmF3OwDv-0)

## Screenshot reference

<img width="895" alt="Screenshot 2024-05-28 at 11 17 33 AM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/9f5c7032-8c1b-4505-96b3-09dad4947044">

**Comment by Khaalid-oh** [comment]
I can help with this
