### ISSUE TITLE
New design for "drag and drop" view on Chat

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#407]
Apply the new designs to the view that show while dragging a file over the chat view

**_Base branch: test-flight_**

## General requirements
- All **assets** needs to be taken from Figma (export in 3x and create them adding versions for 1x, 2x and 3x in Assets section of the project)
- All colors need to be taken from Figma (some of them already exist in the project, some others need to be created). All new colors need to be created for both **dark and light** mode in the Color section of the app
- All **sizes, margins**, etc need to be taken from Figma.
- Apply the new designs to the existing dragging view (`DraggingDestinationView.xib / DraggingDestinationView.swift`)

**Acceptance Criteria**

- [ ] Apply all designs with right sizes, colors and assets for both dark and light mode
- [ ] Record a video with loom for review when task is completed

Figma designs: first view on the left accessing the following Figma link
[https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4259-25280&t=NySmzOLmrAhHo9fi-0](https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4259-25280&t=NySmzOLmrAhHo9fi-0)

## Screenshot reference

<img width="695" alt="Screenshot 2024-06-05 at 11 11 26 AM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/0a2b4785-6f59-4b06-af3c-4cb8a0fe57c0">

**Comment by Khaalid-oh** [comment]
I can help
