### ISSUE TITLE
New design for + button menu on Chat

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#408]
Apply the new designs to the + button menu on chat

**_Base branch: test-flight_**

## General requirements
- All **assets** needs to be taken from Figma (export in 3x and create them adding versions for 1x, 2x and 3x in Assets section of the project)
- All colors need to be taken from Figma (some of them already exist in the project, some others need to be created). All new colors need to be created for both **dark and light** mode in the Color section of the app
- All **sizes, margins**, etc need to be taken from Figma.

## Specific requirements
- Apply the new designs to the + button menu on Chat replacing the existing menu
- Existing menu has 2 options (SEND and RECEIVE). The new menu will have a first new option FILE
- Design of the menu: hover and pressed state are detailed in Figma (in a separated view above the menu design). Menu should be consistent with the new mentions menu we merged recently

**Acceptance Criteria**

- [ ] Apply all designs with right sizes, colors and assets for both dark and light mode
- [ ] Record a video with loom for review when task is completed

Figma designs: second view on the left accessing the following Figma link
[https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4259-25280&t=NySmzOLmrAhHo9fi-0](https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4259-25280&t=NySmzOLmrAhHo9fi-0)

## Screenshot reference

<img width="699" alt="Screenshot 2024-06-05 at 11 11 39 AM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/d7f83728-7228-480d-9a7d-5dc4be37bd03">

**Comment by Khaalid-oh** [comment]
I can help
