### ISSUE TITLE
New designs for attachments preview on Chat

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#409]
Build the UI of the new multi attachments preview on Chat

**_Base branch: test-flight_**

## General requirements
- All **assets** needs to be taken from Figma (export in 3x and create them adding versions for 1x, 2x and 3x in Assets section of the project)
- All colors need to be taken from Figma (some of them already exist in the project, some others need to be created). All new colors need to be created for both **dark and light** mode in the Color section of the app
- All **sizes, margins**, etc need to be taken from Figma.

## Specific requirements
- Build the new UI for multi attachments preview on Chat (existing attachment preview supports one attachment at a time and shows over the chat)
- New design shows attachment previews as an expansion of the message fiel in the bottom bar, allowing to show multiple attachments in a horizontally scrollable area. 
- This ticket DOES NOT involve logic related with sending multiple attachments at a time.

**Acceptance Criteria**

- [ ] Apply all designs with right sizes, colors and assets for both dark and light mode
- [ ] Record a video with loom for review when task is completed

Figma designs: third, forth and fifth views from the left accessing the following Figma link
[https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4259-25280&t=NySmzOLmrAhHo9fi-0](https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4259-25280&t=NySmzOLmrAhHo9fi-0)

## Screenshot reference

**_Old Attachment Preview_**
<img width="1294" alt="Screenshot 2024-06-05 at 11 26 36 AM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/51c1191f-bd71-4c0b-80c4-9607736d174b">

**_New Attachments Preview_**
<img width="806" alt="Screenshot 2024-06-05 at 11 12 06 AM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/28f98df7-457b-44b0-8213-4950a608c8e3">

**Comment by Khaalid-oh** [comment]
I can help with this
