### ISSUE TITLE
Mentions in tribes

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-mac#41]
In the Stakwork Devel tribe, we can @mention several people but for some reason Chase and Michael doesn't work but everyone else does. 
No suggestions pop up.

**Comment by tomastiminskas** [comment]
We used the previous messages in the chat to get aliases of members (sender_alias attribute on each message). So if they never sent a message in that tribe the alias won't appear. Could that be the case?

**Comment by tomastiminskas** [comment]
Right now we are getting nicknames for mentions menu based on all existing restored messages on that tribe. We don't have a way to get all members on a tribe other that iterating through all messages. So I'm closing this for now since we are doing what the current privacy settings allow us to do
