### ISSUE TITLE
Allow drag and drop of multiple files

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#413]
Based on the new multiple attachments preview view, we should now allow dragging and dropping multiple files at a time (up to 10) since right now the drag and drop feature allows just 1 file at a time. 

In addition the new attachments preview view should support up to 10 files. So if adding one by one or multiple files at a time, it should stop adding them when you reach the limit of 10

**Comment by Khaalid-oh** [comment]
I can help with this

**Comment by ramishj** [comment]
Please Assign me the task

**Comment by tomastiminskas** [comment]
@ramishj this is already assigned to someone else!

**Comment by ramishj** [comment]
> @ramishj this is already assigned to someone else!

So i can't try this?
