### ISSUE TITLE
Share Public Key improvements

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#414]
Build the UI of the new Share Public Key view

**_Base branch: test-flight_**

## General requirements
- All **assets** needs to be taken from Figma (export in 3x and create them adding versions for 1x, 2x and 3x in Assets section of the project)
- All colors need to be taken from Figma (some of them already exist in the project, some others need to be created). All new colors need to be created for both **dark and light** mode in the Color section of the app
- All **sizes, margins**, etc need to be taken from Figma.

## Specific requirements
- Build the new UI for Share Public Key view
- Add new QR code button in Chats List header
- Add the new button "Connect with Friend" in left menu

**Acceptance Criteria**

- [ ] Apply all designs with right sizes, colors and assets for both dark and light mode
- [ ] Record a video with loom for review when task is completed

Figma designs: https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4869-24500&t=hvcPqa8nfUNI3zeh-0

## Screenshot reference

**_New buttons on Chats list header and left menu_**
<img width="377" alt="Screenshot 2024-06-25 at 2 36 49 PM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/e5f69bb4-8946-44da-a7ad-f00e01a00016">

**_Old Share Public Key View_**
<img width="444" alt="Screenshot 2024-06-25 at 11 17 51 AM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/1d57ab87-4138-4db7-b02b-addcc4fb2044">

**_New Share Public Key View_**
<img width="388" alt="Screenshot 2024-06-25 at 2 35 22 PM" src="https://github.com/stakwork/sphinx-mac/assets/2242281/f8b0f825-39fa-44ab-bd5c-bdd7f0c671d9">

**Comment by Khaalid-oh** [comment]
I can help with this
