### ISSUE TITLE
Boost not showing 

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-mac#44]
I boosted this msg in build 248
I think it's related to the fact that a file is attached, since boosts show up for text msgs.
The row for the boost appears but the contents do show, even after leaving and re-entering the tribe:

<img width="313" alt="Screenshot 2023-03-04 at 7 59 49 PM" src="https://user-images.githubusercontent.com/814886/222939334-dc82fdc8-3e86-43f4-b496-2a1d4d4b5c6c.png">

**Comment by tomastiminskas** [comment]
Fixed this on both iOS and Mac. It was an easy fix and it's ready to be included on next releases for both platforms
