### ISSUE TITLE
Multiple links in text message

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-mac#54]
If two links are back to back, it's not possible to tap the first link. The second always opens. We need a way to handle links better in message blocks. 
The"..." menu presents an option to "Copy Link" which grabs the first link.

<img width="513" alt="Screenshot 2023-03-14 at 12 21 25 PM" src="https://user-images.githubusercontent.com/814886/225101248-18fd1fe3-3150-4f4c-bfc7-4bf7c8f81eea.png">

**Comment by uncleJim21** [comment]
I suspect @tomastiminskas issued a fix or that my recent fix to #89 fixed this. I just tried this and it worked. Tom correct me if I'm wrong.
