### ISSUE TITLE
2nd Brain Cache Not Clearing

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-mac#56]
made attempt on https://github.com/stakwork/sphinx-mac/tree/jc/fix/clear-2ndBrain-cache and ran experiment with @kevkevinpal to no avail.

**Comment by jimBeaux27** [comment]
I think @tomastiminskas may have found a way to do this that has been shipping for a little bit. Can you comment @kevkevinpal ?

**Comment by tomastiminskas** [comment]
@jimBeaux27 @kevkevinpal Actually I did a change that I'm almost sure would fix it as Jim said. But never found a way to test it on my side
