### ISSUE TITLE
Encryption Error when Drag & Drop to upload image, but file still uploads after a few mins

### ISSUE THREAD

**Issue by Edvardoh** [stakwork/sphinx-mac#58]
When I drag & drop a file to upload an image to a message or tribe, it throws an "Encryption Error".

I click "OK" and then after a few minutes, the file upload goes through and shows up in the message feed.

See video:
https://user-images.githubusercontent.com/5913805/225737625-057708cd-4af8-4e08-83c6-403795ce2640.mov

MacOS 13.1
Sphinx version: Version 1.1.0 (249)

**Comment by tomastiminskas** [comment]
Fixed
