### ISSUE TITLE
Profile pics mixed up

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-mac#59]
On build 249
These messages are from David, but show the profile pics from two other users.
Leaving the chat and going back in fixed the issue.
David doesn't have a profile image, which may play a role in the bug.

<img width="596" alt="Screenshot 2023-03-22 at 1 24 30 PM" src="https://user-images.githubusercontent.com/814886/227014746-2cb3fe38-db3e-4d00-880f-e0fc21d09928.png">

**Comment by tomastiminskas** [comment]
Closing this because it seems to be fixed. Let's reopen if anyone experience or report it again @tomsmith8
