### ISSUE TITLE
URL previews aren't clickable

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-mac#8]
When receiving a msg with a link, the preview shows, but tapping on the msg box or link does not open the page in the default browser.
<img width="540" alt="Screen Shot 2022-01-06 at 11 07 16 AM" src="https://user-images.githubusercontent.com/814886/148429804-cf482ee4-6efe-404c-b63a-c9eae8849523.png">

**Comment by jimBeaux27** [comment]
I confirmed this is addressed on the latest build so I am closing it.
