### ISSUE TITLE
Don't see mention notification icon

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-mac#90]
I am on Version 1.1.0 (259) of the Mac App.
This also does not work on my Version 1.1.0 (339) of the iOS App.

When I get a mention in a tribe, I don't get the separate "@" icon in the left sidebar. For example:
<img width="384" alt="Screenshot 2023-05-17 at 10 30 27 AM" src="https://github.com/stakwork/sphinx-mac/assets/104323003/b8d04e17-fdd2-4895-8f18-aa2931e19074">

**Comment by tomastiminskas** [comment]
@soup20 found the issue and working on the fix. I will release a version with the fix today or tomorrow at most
